spring.application.name=ErrorFreeText
spring.datasource.url=postgresql://db:5432/errorfreetext?currentSchema=public
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port= 8080
spring.liquibase.change-log=db/changelog/changelog-root.xml
spring.jpa.show-sql=true

fixed.rate=${FIXED_RATE:60000}
chars.limit=${CHARS_LIMIT:10000000}
execution.limit=${EXECUTION_LIMIT:10000}
request.limit=${REQUEST_LIMIT:10000}
