spring.application.name=ErrorFreeText
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=errorfreetext2
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port= 9090
spring.liquibase.change-log=db/changelog/changelog-root.xml
spring.jpa.show-sql=true

fixed.rate=60000
chars.limit=10000000
execution.limit=10000
request.limit=10000

#jdbc:postgresql://db:5432/errorfreetext?currentSchema=public