spring.application.name=ErrorFreeText
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=errorfreetext
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port= 9090
spring.liquibase.change-log=db/changelog/changelog-root.xml

fixed.rate=60000
no.such.id.exception.message = ""
validate.request.text.message= The text must contain more than 3 characters and include more than just special characters and numbers


#jdbc:postgresql://db:5432/errorfreetext?currentSchema=public